routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/discussion', function () {
    return view('discussion.index');
});

Auth::routes();

Route::get('/forum', 'ForumController@index')->name('forum');
Route::get('channel/{id}', 'ForumController@channel')->name('channel');

// Custom route

Route::get('{provider}/auth', [
    'uses' => 'SocialController@auth',
    'as' => 'social.auth'
]);

Route::get('{provider}/redirect', [
    'uses' => 'SocialController@auth_callback',
    'as' => 'social.auth_callback'
]);

Route::get('discussion/{id}/{slug}', [
    'uses' =>'DiscussionController@show',
    'as' => 'discussion.show'
]);
Route::group(['middleware' => 'auth'], function () {
    Route::resource('channel', 'ChannelController');

    Route::get('discussion/create', [
        'uses' =>'DiscussionController@create',
        'as' => 'discussion.create'
    ]);
    Route::get('discussion/update/{slug}/{id}', [
        'uses' =>'DiscussionController@edit',
        'as' => 'discussion.edit'
    ]);
    Route::post('discussion/update/{id}', [
        'uses' =>'DiscussionController@update',
        'as' => 'discussion.update'
    ]);
    Route::post('discussion/store', [
        'uses' =>'DiscussionController@store',
        'as' => 'discussion.store'
    ]);

    Route::post('discussion/reply/{id}', [
        'uses' =>'DiscussionController@reply',
        'as' => 'discussion.reply'
    ]);
    Route::get('reply/like/{id}', [
        'uses' =>'ReplyController@like',
        'as' => 'reply.like'
    ]);
    Route::get('reply/unlike/{id}', [
        'uses' =>'ReplyController@unlike',
        'as' => 'reply.unlike'
    ]);
    Route::get('reply/edit/{id}', [
        'uses' =>'ReplyController@edit',
        'as' => 'reply.edit'
    ]);
    Route::post('reply/update/{id}', [
        'uses' =>'ReplyController@update',
        'as' => 'reply.update'
    ]);

    Route::get('discussion/best/reply/{id}', [
        'uses' =>'ReplyController@best_answer',
        'as' => 'discussion.best_answer'
    ]);

    // Start watch route

    Route::get('watch/{id}', [
        'uses' =>'WatchController@watch',
        'as' => 'discussion.watch'
    ]);

    Route::get('unwatch/{id}', [
        'uses' =>'WatchController@unwatch',
        'as' => 'discussion.unwatch'
    ]);


});

app/Discussion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Discussion extends Model
{
    protected $fillable= ['title', 'slug','content', 'user_id', 'channel_id'];

    public function channel(){
        return $this->belongsTo(Channel::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function replies(){
        return $this->hasMany(Reply::class);
    }
    public function watches(){
        return $this->hasMany(Watch::class);
    }

    public function is_being_watched_by_auth_user(){
        $user = Auth::id();
        $watchers = array();

        foreach ($this->watches()->get() as $watch){
             array_push($watchers, $watch->user_id);
        }
        if (in_array($user, $watchers)){
            return true;
        }

        else{
            return false;
        }
    }

    public function has_best_answer(){
        $best_answer = false;
        foreach ($this->replies()->get() as $reply){
            if ($reply->best_answer){
                $best_answer = True;
                break;
            }
        }
        return $best_answer;
    }

}

app/Http/Controllers/DiscussionController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Discussion;
use App\Notifications\NewReplyAdded;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Reply;
use Notification;
use Session;


class DiscussionController extends Controller
{
    public function create(){
        return view('discussion.create');
    }
    public function edit($slug, $id){
        $discussion = Discussion::find($id);
        return view('discussion.edit')->with('discussion', $discussion);
    }
    public function store(Request $request){
        $this->validate($request,[
            'title' => 'required',
            'channel' => 'required',
            'discussion' => 'required'
        ]);

        $discussion = Discussion::create([
            'title' => $request->title,
            'slug' => str_slug($request->title),
            'content' => $request->discussion,
            'channel_id' => $request->channel,
            'user_id' => Auth::id()

        ]);
        Session::flash('success', 'Discussion Created Successfully');
        return redirect()->route('discussion.show', ['id'=> $discussion->id,'slug'=> $discussion->slug]);
    }
    public function Update(Request $request, $id){
        $this->validate($request,[
            'discussion' => 'required'
        ]);

        $discussion = Discussion::find($id);
        $discussion->content = $request->discussion;
        $discussion->save();
        Session::flash('success', 'Discussion Update Successfully');
        return redirect()->route('discussion.show', ['id'=> $discussion->id,'slug'=> $discussion->slug]);
    }

    public function show($id, $slug){
        $discussion = Discussion::find($id);
            $best_answer = $discussion->replies()->where('best_answer', 1)->first();
        return view('discussion.show')->with('discussion', $discussion)->with('best_answer', $best_answer);
    }

    public function reply(Request $request,$id){

//        $this->validate($request,[
//            'user_id' => 'required',
//            'discussion_id' => 'required',
//            'content' => 'required'
//        ]);

        $discussion = Discussion::find($id);


        $reply = Reply::create([
            'user_id' => Auth::id(),
            'discussion_id' => $discussion->id,
            'content' => $request->reply
        ]);

        $reply->user->points += 25;
        $reply->user->save();

        $watchers = array();

        foreach ($discussion->watches()->get() as $watch){
            array_push($watchers, $watch->user_id);
        }
//        $email = 'admin@forum4u.net';
        $watchers = User::whereIn('id', $watchers)->get();

//        dd($watchers);

        Notification::send($watchers, New NewReplyAdded($discussion));


        Session::flash('success', 'Replied to the discussion');
        return redirect()->back();
    }
}

resources/views/discussion/create.blade.php
@extends('layouts.app')

@section('content')
            <div class="card">
                <h5 class="card-header text-center">Create a New Discussion</h5>

                <div class="card-body">
                    <form action="{{route('discussion.store')}}" method="post">
                        {{csrf_field()}}
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" value="{{old('title')}}" class="form-control">
                            <label for="channel">Pick a Channel</label>
                            <select class="form-control" name="channel" id="channel">
                                <option value="">--Select a channel--</option>
                            @foreach($channels as $channel)
                                    <option value="{{$channel->id}}">{{$channel->title}}</option>
                                    @endforeach
                            </select>
                            <label for="discussion">Ask a Question</label>
                            <textarea type="text" id="editor" name="discussion" class="form-control" cols="30" rows="10">{{old('content')}}</textarea>
                            <br>
                            <button class="form-control btn btn-success" type="submit">
                                Save Discussion
                            </button>
                        </div>

                    </form>
                </div>
            </div>
@endsection

resources/views/discussion/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <h5 class="card-header text-center">Update Discussion</h5>

        <div class="card-body">
            <form action="{{route('discussion.update', ['id'=> $discussion->id])}}" method="post">
                {{csrf_field()}}
                <div class="form-group">
                    <textarea type="text" id="editor" name="discussion" class="form-control" cols="30" rows="10">{{ $discussion->content }}</textarea>
                    <br>
                    <button class="form-control btn btn-success" type="submit">
                        Save discussion changes
                    </button>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/discussion/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Channels</div>

        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            <table class="table table-hover">
                <thead>
                <th>
                    Name
                </th>
                <th>
                    Edit
                </th>
                <th>
                    Delete
                </th>
                </thead>
                <tbody>
                @foreach($channels as $channel)
                    <tr>
                        <td>{{$channel->title}}</td>
                        <td><a href="{{route('channel.edit', ['channel'=> $channel->id])}}" class=" btn btn-xs btn-info">Edit</a></td>
                        <td>
                            <form action="{{route('channel.destroy', ['channel'=> $channel->id])}}" method="post">
                                {{csrf_field()}}
                                {{method_field('delete')}}
                                <button class="btn btn-xs btn-danger" type="submit">Delete</button>

                            </form>
                        </td>

                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>
    </div>

@endsection

resources/views/discussion/show.blade.php
@extends('layouts.app')
@section('title', $discussion->title)
@section('content')
    <div class="card">
        <div class="card-header">
            <img class="rounded-circle" src="{{ asset($discussion->user->avatar) }}" alt="Logo" width="40px" height="40px">
            <span class="text-muted"> Discussed by - {{$discussion->user->name}} ({{$discussion->user->points}}) || <b>{{$discussion->created_at->diffForHumans()}}</b></span>
            @if(Auth::id() == $discussion->user_id and !$discussion->has_best_answer())
                <a class=" float-right btn btn-outline-info btn-sm text-decoration-none ml-1"
                   href="{{route('discussion.edit', ['slug'=>$discussion->slug, 'id' => $discussion->id])}}">Edit</a>
            @endif
            @if($discussion->is_being_watched_by_auth_user())
                <a class=" float-right btn btn-outline-danger btn-sm text-decoration-none ml-1"
                   href="{{route('discussion.unwatch', ['id' => $discussion->id])}}">Unwatch</a>
            @else
                <a class=" float-right btn btn-outline-success btn-sm text-decoration-none ml-1"
                   href="{{route('discussion.watch', ['id' => $discussion->id])}}">Watch</a>
            @endif
            @if($discussion->has_best_answer())
                <span class="btn btn-success btn-sm float-right">Open</span>

            @else
                <span class="btn btn-danger btn-sm float-right ">Close</span>

            @endif
        </div>
        <div class="card-body">
            <h4> {{$discussion->title}}</h4>
            {!! Markdown::convertToHtml($discussion->content) !!}
            @if($best_answer)
                <div class="text-center card border-success ">
                    <div class=" card-body">
                        <h3 class="text-center">Best Answer</h3>
                        <img class="rounded-circle" src="{{ asset($discussion->user->avatar) }}" alt="Logo" width="70px" height="70px">
                        <span class=""> Answered  by - {{$best_answer->user->name}} ({{$best_answer->user->points}})</span>
                        <hr>
                        <p class="text-justify border-success"> {!! Markdown::convertToHtml($best_answer->content) !!} </p>
                    </div>
                </div>
            @endif
        </div>
        <div class="card-footer">
            <span>{{$discussion->replies->count()}} replies</span>
            <a class=" float-right btn btn-outline-primary btn-sm text-decoration-none"
               href="{{route('channel', ['id'=>$discussion->channel->id, 'slug'=>$discussion->channel->slug])}}">{{$discussion->channel->title}}</a>
        </div>
    </div>
    <br>
    @foreach($discussion->replies as $r)
        <div class="card">
            <div class="card-header">
                <img class="rounded-circle" src="{{ asset($r->user->avatar) }}" alt="Logo" width="40px" height="40px">
                <span class="text-muted"> Replied by - {{$r->user->name}} || <b>{{$r->created_at->diffForHumans()}} (reply)</b></span>
                @if(!$best_answer)
                    @if(Auth::id()== $discussion->user->id)
                        <a href="{{route('discussion.best_answer', ['id'=> $r->id])}}" class="btn btn-sm btn-info float-right">Mark as best answer</a>
                    @endif
                    @if(Auth::id()== $r->user->id)
                        <a href="{{route('reply.edit', ['id'=> $r->id])}}" class="btn btn-sm btn-info float-right mr-1">Edit</a>
                    @endif
                @endif

            </div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                    {!! Markdown::convertToHtml($r->content ) !!}
            </div>
            <div class="card-footer text-muted">
                @if($r->is_liked_by_auth_user())
                    <a href="{{route('reply.unlike', ['id' => $r->id])}}" class="btn btn-danger btn-sm">Unlike <span class="badge badge-pill badge-dark">{{$r->likes->count()}}</span></a>
                @else
                    <a href="{{route('reply.like', ['id' => $r->id])}}" class="btn btn-success btn-sm">Like <span class="badge badge-pill badge-dark">{{$r->likes->count()}}</span></a>
                @endif
            </div>
        </div>
        <br>
    @endforeach

    <div class="card">
        <div class="card-body">
            @if(Auth::check())
                <div class="form-group">
                    <form action="{{route('discussion.reply', ['id'=> $discussion->id])}}" method="post">
                        {{csrf_field()}}
                        <label for="reply">Leave a reply</label>
                        <textarea class="form-control" name="reply" id="editor" cols="30" rows="10"></textarea>
                        <br>
                        <button class=" btn btn-xs btn-success " type="submit">
                            Reply
                        </button>
                    </form>
                </div>
            @else
                <div class="text-center">
                    <h2>Sign in to leave a reply</h2>
                </div>
            @endif

        </div>
    </div>
    {{--    </div>--}}
@endsection