routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/discussion', function () {
    return view('discussion.index');
});

Auth::routes();

Route::get('/forum', 'ForumController@index')->name('forum');
Route::get('channel/{id}', 'ForumController@channel')->name('channel');

// Custom route

Route::get('{provider}/auth', [
    'uses' => 'SocialController@auth',
    'as' => 'social.auth'
]);

Route::get('{provider}/redirect', [
    'uses' => 'SocialController@auth_callback',
    'as' => 'social.auth_callback'
]);

Route::get('discussion/{id}/{slug}', [
    'uses' =>'DiscussionController@show',
    'as' => 'discussion.show'
]);
Route::group(['middleware' => 'auth'], function () {
    Route::resource('channel', 'ChannelController');

    Route::get('discussion/create', [
        'uses' =>'DiscussionController@create',
        'as' => 'discussion.create'
    ]);
    Route::get('discussion/update/{slug}/{id}', [
        'uses' =>'DiscussionController@edit',
        'as' => 'discussion.edit'
    ]);
    Route::post('discussion/update/{id}', [
        'uses' =>'DiscussionController@update',
        'as' => 'discussion.update'
    ]);
    Route::post('discussion/store', [
        'uses' =>'DiscussionController@store',
        'as' => 'discussion.store'
    ]);

    Route::post('discussion/reply/{id}', [
        'uses' =>'DiscussionController@reply',
        'as' => 'discussion.reply'
    ]);
    Route::get('reply/like/{id}', [
        'uses' =>'ReplyController@like',
        'as' => 'reply.like'
    ]);
    Route::get('reply/unlike/{id}', [
        'uses' =>'ReplyController@unlike',
        'as' => 'reply.unlike'
    ]);
    Route::get('reply/edit/{id}', [
        'uses' =>'ReplyController@edit',
        'as' => 'reply.edit'
    ]);
    Route::post('reply/update/{id}', [
        'uses' =>'ReplyController@update',
        'as' => 'reply.update'
    ]);

    Route::get('discussion/best/reply/{id}', [
        'uses' =>'ReplyController@best_answer',
        'as' => 'discussion.best_answer'
    ]);

    // Start watch route

    Route::get('watch/{id}', [
        'uses' =>'WatchController@watch',
        'as' => 'discussion.watch'
    ]);

    Route::get('unwatch/{id}', [
        'uses' =>'WatchController@unwatch',
        'as' => 'discussion.unwatch'
    ]);


});

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    protected $fillable = ['title', 'slug'];

    public function discussions(){
        return $this->hasMany('App\Discussion');
    }
}

app/Http/Controllers/ChannelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Channel;
use Session;
use function GuzzleHttp\Psr7\str;

class ChannelController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        return view('channel.index')->with('channels', Channel::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('channel.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'channel' => 'required',
            'slug' => 'required'
        ]);

        Channel::create([
            'title'=> $request->channel,
            'slug' => str_slug($request->channel)

        ]);

        Session::flash('Success', 'New channel created');
        return redirect()->route('channel.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $channel = Channel::find($id);
        return view('channel.edit')->with('channel', $channel);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request,[
            'channel' => 'required',
        ]);

        $channel = Channel::find($id);
        $channel->title = $request->channel;
        $channel->slug = str_slug($request->channel);
        $channel->save();

        Session::flash('success', 'New channel Edited');
        return redirect()->route('channel.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $channel = Channel::destroy($id);

        Session::flash('Success', 'New channel Edited');
        return redirect()->route('channel.index');
    }
}

resources/views/channel/create.blade.php
@extends('layouts.app')

@section('content')
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{route('channel.store')}}" method="post">
                            {{csrf_field()}}
                            <div class="form-group">
                                <input type="input" name="channel" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success text-center" type="submit">
                                    Save Channel
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
@endsection

resources/views/channel/edit.blade.php
@extends('layouts.app')

@section('content')

                <div class="card">
                    <div class="card-header">Edit Channel: {{$channel->title}}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{route('channel.update', ['channel'=> $channel->id])}}" method="post">
                            {{csrf_field()}}
                            {{method_field('put')}}
                            <div class="form-group">
                                <input type="input" name="channel" value="{{$channel->title}}" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success text-center" type="submit">
                                    Save Update
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
@endsection

resources/views/channel/index.blade.php
@extends('layouts.app')
@section('title', 'All Channels')

@section('content')
    <div class="card">
        <div class="card-header">Channels</div>

        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            <table class="table table-hover">
                <thead>
                <th>
                    Name
                </th>
                <th>
                    Edit
                </th>
                <th>
                    Delete
                </th>
                </thead>
                <tbody>
                @foreach($channels as $channel)
                    <tr>
                        <td>{{$channel->title}}</td>
                        <td><a href="{{route('channel.edit', ['channel'=> $channel->id])}}" class=" btn btn-xs btn-info">Edit</a></td>
                        <td>
                            <form action="{{route('channel.destroy', ['channel'=> $channel->id])}}" method="post">
                                {{csrf_field()}}
                                {{method_field('delete')}}
                                <button class="btn btn-xs btn-danger" type="submit">Delete</button>

                            </form>
                        </td>

                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>
    </div>
@endsection