routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/discussion', function () {
    return view('discussion.index');
});

Auth::routes();

Route::get('/forum', 'ForumController@index')->name('forum');
Route::get('channel/{id}', 'ForumController@channel')->name('channel');

// Custom route

Route::get('{provider}/auth', [
    'uses' => 'SocialController@auth',
    'as' => 'social.auth'
]);

Route::get('{provider}/redirect', [
    'uses' => 'SocialController@auth_callback',
    'as' => 'social.auth_callback'
]);

Route::get('discussion/{id}/{slug}', [
    'uses' =>'DiscussionController@show',
    'as' => 'discussion.show'
]);
Route::group(['middleware' => 'auth'], function () {
    Route::resource('channel', 'ChannelController');

    Route::get('discussion/create', [
        'uses' =>'DiscussionController@create',
        'as' => 'discussion.create'
    ]);
    Route::get('discussion/update/{slug}/{id}', [
        'uses' =>'DiscussionController@edit',
        'as' => 'discussion.edit'
    ]);
    Route::post('discussion/update/{id}', [
        'uses' =>'DiscussionController@update',
        'as' => 'discussion.update'
    ]);
    Route::post('discussion/store', [
        'uses' =>'DiscussionController@store',
        'as' => 'discussion.store'
    ]);

    Route::post('discussion/reply/{id}', [
        'uses' =>'DiscussionController@reply',
        'as' => 'discussion.reply'
    ]);
    Route::get('reply/like/{id}', [
        'uses' =>'ReplyController@like',
        'as' => 'reply.like'
    ]);
    Route::get('reply/unlike/{id}', [
        'uses' =>'ReplyController@unlike',
        'as' => 'reply.unlike'
    ]);
    Route::get('reply/edit/{id}', [
        'uses' =>'ReplyController@edit',
        'as' => 'reply.edit'
    ]);
    Route::post('reply/update/{id}', [
        'uses' =>'ReplyController@update',
        'as' => 'reply.update'
    ]);

    Route::get('discussion/best/reply/{id}', [
        'uses' =>'ReplyController@best_answer',
        'as' => 'discussion.best_answer'
    ]);

    // Start watch route

    Route::get('watch/{id}', [
        'uses' =>'WatchController@watch',
        'as' => 'discussion.watch'
    ]);

    Route::get('unwatch/{id}', [
        'uses' =>'WatchController@unwatch',
        'as' => 'discussion.unwatch'
    ]);


});

resources/views/_partial/channel.blade.php
<a href="{{route('discussion.create')}}" class=" form-control btn btn-primary">Create Discussion</a>
<br>
<br>
<div class="card">
    <div class="card-body">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="/forum" style="text-decoration:none">Home</a>
            </li>
            <li class="list-group-item">
                <a href="/forum?filter=me" style="text-decoration:none">My Discussion</a>
            </li>
            <li class="list-group-item">
                <a href="/forum?filter=solved" style="text-decoration:none">Solved Discussion</a>
            </li>
            <li class="list-group-item">
                <a href="/forum?filter=unsolved" style="text-decoration:none">Unsolved Discussion</a>
            </li>
        </ul>
    </div>
    @if(Auth::check())
        @if(Auth::user()->admin)
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="{{route('channel.index')}} " style="text-decoration:none">All Channels</a>
                    </li>
                </ul>
            </div>
            @endif
    @endif
</div>

<br>
<div class="card">
    <div class="card-header">
        Channels
    </div>

    <div class="card-body">
        <ul class="list-group">
            @foreach($channels as $channel)
                <li class="list-group-item">
                    <a class="text-decoration-none" href="{{route('channel', ['id'=>$channel->id])}}">{{$channel->title}}</a>
                </li>
            @endforeach
        </ul>
    </div>
</div>

resources/views/_partial/footer.blade.php
<script src="{{asset('js/jquery.min.js')}}"></script>
<script src="{{asset('js/popper.min.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>
<script src="{{asset('js/toastr.min.js')}}"></script>
<script src="{{asset('js/highlight.pack.min.js')}}"></script>
<script src="{{asset('js/ckeditor.js')}}"></script>
{{--<script src="{{asset('js/fontawesome.min.js')}}"></script>--}}

resources/views/_partial/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>forum4u - @yield('title') </title>

<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

<!-- Styles -->
<link rel="stylesheet" type="text/css" href="{{asset('css/style.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/toastr.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/solarized-dark.min.css')}}">
{{--<link rel="stylesheet" type="text/css" href="{{asset('css/font-awesome.min.css')}}">--}}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

resources/views/_partial/nav.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            Forum4U
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
                @endif
                @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>